export const LEASES_REQUESTED = 'LEASES_REQUESTED';
export const LEASES_COMPLETED = 'LEASES_COMPLETED';
export const LEASES_FAILED = 'LEASES_FAILED';
export const LEASE_DETAILS_REQUESTED = 'LEASE_DETAILS_REQUESTED';
export const LEASE_DETAILS_COMPLETED = 'LEASE_DETAILS_COMPLETED';
export const LEASE_DETAILS_FAILED = 'LEASE_DETAILS_FAILED';
